CREATE TABLE `urls` (
  `UID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `LONG_URL` varchar(255) DEFAULT '',
  `SHORT_URL` varbinary(6) DEFAULT '',
  `DATE_CREATED` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`UID`),
  KEY `SHORT_URL` (`SHORT_URL`)
) ENGINE=InnoDB AUTO_INCREMENT=130 DEFAULT CHARSET=latin1;